name: Velog Backup

on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정에 실행 (원하는 시간대로 수정 가능)
  workflow_dispatch: # 수동 실행

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Fetch and backup Velog posts
        env:
          VELOG_USERNAME: "yohan9569"
        run: |
          mkdir -p velog-posts
          node -e "
          const fs = require('fs');
          const axios = require('axios');
          
          const username = process.env.VELOG_USERNAME;
          axios.get(\`https://velog.io/api/@${username}/posts\`)
            .then(response => {
              response.data.forEach(post => {
                const content = \`# \${post.title}\n\n\${post.body}\`;
                const filePath = \`velog-posts/\${post.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.md\`;
                fs.writeFileSync(filePath, content);
              });
            })
            .catch(err => console.error('Error fetching Velog posts:', err));
          "

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "yohan9569@gmail.com"
          git config --local user.name "yohan9569"
          git add velog-posts/*.md
          git commit -m "Auto backup Velog posts"
          git push
